-- ============================================================================
-- DCI Dashboard — Supabase PostgreSQL schema
-- Run this once in the Supabase SQL editor (or via `supabase db push`).
-- Safe to re-run: every statement is guarded with IF NOT EXISTS / OR REPLACE.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. imports  — one row per uploaded workbook / version
-- ----------------------------------------------------------------------------
create table if not exists imports (
    id                      bigint generated by default as identity primary key,
    original_filename       text not null,
    display_name             text,
    project_name             text,
    contractor                text,
    version_number            integer not null default 1,
    parent_import_id          bigint references imports(id),
    uploaded_at                timestamptz not null default now(),
    uploaded_by                 text,
    source_sheet_name           text not null default 'DCI',
    row_count                    integer not null default 0,
    workbook_hash                 text,
    storage_bucket                 text not null default 'dci-workbooks',
    original_storage_path           text not null,
    review_period_days               integer not null default 21,
    validation_status                 text,
    import_status                      text not null default 'pending', -- pending | complete | failed | archived
    warning_count                       integer not null default 0,
    error_count                          integer not null default 0,
    is_active                             boolean not null default true,
    created_at                             timestamptz not null default now(),
    updated_at                              timestamptz not null default now()
);

create index if not exists idx_imports_hash on imports(workbook_hash);
create index if not exists idx_imports_active on imports(is_active);

-- ----------------------------------------------------------------------------
-- 2. documents — current/latest state of every document (one row = one doc)
-- ----------------------------------------------------------------------------
create table if not exists documents (
    id                          bigint generated by default as identity primary key,
    import_id                    bigint not null references imports(id) on delete cascade,
    document_key                  text not null,
    original_row_number            integer not null,
    document_number                  text,
    document_title                    text,
    discipline                         text,
    vendor                               text,
    document_type                        text,
    revision                              text,
    dci_status                             text,
    returned_code                           text,
    planned_submission_date                  date,
    actual_submission_date                    date,
    review_date                                date,
    approval_date                               date,
    forecast_month                               text,
    remarks                                       text,
    assigned_engineer                              text,
    action_owner                                    text,
    expected_completion_date                         date,
    lifecycle_stage                                   text,
    aging_days                                         integer,
    last_changed_by                                     text,
    is_active                                            boolean not null default true,
    created_at                                            timestamptz not null default now(),
    updated_at                                             timestamptz not null default now(),
    unique(import_id, document_key)
);

create index if not exists idx_documents_import_id on documents(import_id);
create index if not exists idx_documents_status on documents(dci_status);
create index if not exists idx_documents_discipline on documents(discipline);
create index if not exists idx_documents_vendor on documents(vendor);
create index if not exists idx_documents_revision on documents(revision);
create index if not exists idx_documents_number on documents(document_number);

-- ----------------------------------------------------------------------------
-- 3. document_raw_data — full original row (all Excel columns) as JSONB,
--    plus that document's revision-history block rows, so nothing the
--    dashboard doesn't explicitly model gets lost, and exports can be
--    reconstructed faithfully.
-- ----------------------------------------------------------------------------
create table if not exists document_raw_data (
    id                        bigint generated by default as identity primary key,
    document_id                bigint not null unique references documents(id) on delete cascade,
    row_data                     jsonb not null,   -- {"record": {...}, "history_rows": [...]}
    original_column_names          jsonb,
    original_row_number              integer not null,
    last_synchronized_at               timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 4. document_history — append-only audit trail
-- ----------------------------------------------------------------------------
create table if not exists document_history (
    id                    bigint generated by default as identity primary key,
    document_id            bigint not null references documents(id) on delete cascade,
    import_id                bigint not null references imports(id) on delete cascade,
    event_type                 text not null,
    field_name                   text,
    old_value                     text,
    new_value                      text,
    revision                        text,
    returned_code                    text,
    status                             text,
    remarks                             text,
    changed_by                           text,
    changed_at                             timestamptz not null default now(),
    source                                   text not null default 'dashboard',
    import_version                            integer
);

create index if not exists idx_history_document_id on document_history(document_id);
create index if not exists idx_history_changed_at on document_history(changed_at);

-- ----------------------------------------------------------------------------
-- 5. export_records — log of every generated export
-- ----------------------------------------------------------------------------
create table if not exists export_records (
    id                bigint generated by default as identity primary key,
    import_id           bigint not null references imports(id) on delete cascade,
    export_type           text not null,   -- workbook | history_report | register_csv
    exported_by             text,
    exported_at               timestamptz not null default now(),
    filename                    text not null,
    storage_path                  text,
    row_count                       integer,
    success                           boolean not null default true,
    error_message                      text
);

create index if not exists idx_export_records_import_id on export_records(import_id);

-- ----------------------------------------------------------------------------
-- 6. fn_save_document_changes — atomic "update + history" RPC
--    Called from the app with a JSONB object of {field_name: new_value}
--    covering only the fields the user actually changed. Performs the
--    documents update, patches document_raw_data.row_data->'record', and
--    inserts one document_history row per changed field, all in one
--    transaction (a single function call is one implicit Postgres transaction).
-- ----------------------------------------------------------------------------
create or replace function fn_save_document_changes(
    p_document_id bigint,
    p_changes jsonb,          -- {"dci_status": "APPROVED", "remarks": "..."} etc (new values, text-cast)
    p_old_values jsonb,       -- same keys, previous values, for the history row
    p_event_type text,
    p_changed_by text
) returns jsonb
language plpgsql
as $$
declare
    v_import_id bigint;
    v_key text;
    v_new text;
    v_old text;
    v_revision text;
    v_returned_code text;
    v_status text;
    v_remarks text;
begin
    select import_id into v_import_id from documents where id = p_document_id;
    if v_import_id is null then
        raise exception 'Document % not found', p_document_id;
    end if;

    -- Apply the changes to the documents row (only known editable columns).
    update documents set
        document_title            = coalesce(p_changes->>'document_title', document_title),
        revision                    = coalesce(p_changes->>'revision', revision),
        dci_status                    = coalesce(p_changes->>'dci_status', dci_status),
        returned_code                    = coalesce(p_changes->>'returned_code', returned_code),
        planned_submission_date            = case when p_changes ? 'planned_submission_date'
                                                     then nullif(p_changes->>'planned_submission_date','')::date
                                                     else planned_submission_date end,
        actual_submission_date               = case when p_changes ? 'actual_submission_date'
                                                     then nullif(p_changes->>'actual_submission_date','')::date
                                                     else actual_submission_date end,
        review_date                             = case when p_changes ? 'review_date'
                                                     then nullif(p_changes->>'review_date','')::date
                                                     else review_date end,
        approval_date                              = case when p_changes ? 'approval_date'
                                                     then nullif(p_changes->>'approval_date','')::date
                                                     else approval_date end,
        expected_completion_date                      = case when p_changes ? 'expected_completion_date'
                                                     then nullif(p_changes->>'expected_completion_date','')::date
                                                     else expected_completion_date end,
        forecast_month                                   = coalesce(p_changes->>'forecast_month', forecast_month),
        remarks                                             = coalesce(p_changes->>'remarks', remarks),
        assigned_engineer                                     = coalesce(p_changes->>'assigned_engineer', assigned_engineer),
        action_owner                                             = coalesce(p_changes->>'action_owner', action_owner),
        last_changed_by                                            = p_changed_by,
        updated_at                                                   = now()
    where id = p_document_id;

    -- Patch the raw JSON snapshot so future exports/reloads see the new values too.
    update document_raw_data
    set row_data = jsonb_set(
            row_data,
            '{record}',
            (row_data->'record') || p_changes,
            true
        ),
        last_synchronized_at = now()
    where document_id = p_document_id;

    -- One append-only history row per changed field.
    select dci_status, revision, returned_code, remarks
    into v_status, v_revision, v_returned_code, v_remarks
    from documents where id = p_document_id;

    for v_key in select jsonb_object_keys(p_changes) loop
        v_new := p_changes->>v_key;
        v_old := p_old_values->>v_key;
        if v_old is distinct from v_new then
            insert into document_history (
                document_id, import_id, event_type, field_name,
                old_value, new_value, revision, returned_code, status, remarks,
                changed_by, source
            ) values (
                p_document_id, v_import_id, p_event_type, v_key,
                v_old, v_new, v_revision, v_returned_code, v_status, v_remarks,
                p_changed_by, 'dashboard'
            );
        end if;
    end loop;

    return (select to_jsonb(d) from documents d where id = p_document_id);
end;
$$;
